export interface Category {
    id: string;
    name: string;
    icon: string; // Emoji or icon name
    subcategories: string[];
}

export const CATEGORIES: Category[] = [
    {
        id: 'food',
        name: 'Food & Ingredients',
        icon: '🍲',
        subcategories: [
            'Spices & Seasonings',
            'Pantry Staples (Rice, Flour, Grains)',
            'Dried Proteins (Crayfish, Stockfish, Dried Fish)',
            'Fresh & Frozen (Vegetables, Meats, Seafood)',
            'Sauces & Condiments',
            'Snacks & Sweets',
            'Beverages & Drinks',
            'Baking Ingredients',
            'Meal Kits (Ready-to-Cook)',
            'Homemade Delicacies',
            'Traditional Breads & Pastries',
            'Preserved Foods (Pickles, Jams, Fermented)',
        ],
    },
    {
        id: 'games',
        name: 'Games & Entertainment',
        icon: '🎮',
        subcategories: [
            'Traditional Board Games',
            'Card Games',
            'Dice & Tile Games',
            'Outdoor/Physical Games',
            'Puzzles',
            'Musical Instruments',
            'Books & Novels',
            'Comics & Graphic Novels',
            'Music (Vinyl, CDs, Digital)',
            'Movies & DVDs',
            'Posters & Prints',
            'Toys & Collectibles',
        ],
    },
    {
        id: 'home',
        name: 'Home & Decor',
        icon: '🏺',
        subcategories: [
            'Wall Art & Paintings',
            'Textiles (Curtains, Throws, Cushions)',
            'Rugs & Carpets',
            'Ceramics & Pottery',
            'Sculptures & Figurines',
            'Flags & Banners',
            'Lamps & Lighting',
            'Mirrors',
            'Vases & Planters',
            'Kitchen Decor',
            'Bedroom Decor',
            'Living Room Decor',
            'Bathroom Accessories',
            'Incense & Candles',
        ],
    },
    {
        id: 'fashion',
        name: 'Fashion & Accessories',
        icon: '👗',
        subcategories: [
            'Traditional Wear (Men)',
            'Traditional Wear (Women)',
            'Traditional Wear (Kids)',
            'Modern Ethnic Fashion',
            'Casual Wear with Cultural Prints',
            'Formal/Occasion Wear',
            'Jewelry (Necklaces, Bracelets, Earrings)',
            'Headwear (Hats, Turbans, Wraps)',
            'Footwear (Sandals, Slippers, Shoes)',
            'Bags & Purses',
            'Belts & Sashes',
            'Scarves & Shawls',
            'Hair Accessories',
            'Sunglasses & Eyewear',
        ],
    },
    {
        id: 'crafts',
        name: 'Crafts & Handmade',
        icon: '🎨',
        subcategories: [
            'Woodwork & Carvings',
            'Metalwork & Jewelry Making',
            'Textile Crafts (Weaving, Embroidery)',
            'Leather Goods',
            'Beadwork',
            'Basket Weaving',
            'Pottery & Clay Work',
            'Paper Crafts & Origami',
            'Painting & Drawing Supplies',
            'DIY Craft Kits',
            'Traditional Tools & Utensils',
            'Handmade Toys',
            'Religious/Spiritual Items',
            'Home Improvement Crafts',
        ],
    },
    {
        id: 'beauty',
        name: 'Beauty & Wellness',
        icon: '💄',
        subcategories: [
            'Skincare (Natural/Traditional)',
            'Hair Care Products',
            'Body Care (Oils, Butters, Scrubs)',
            'Soaps & Bath Products',
            'Makeup & Cosmetics',
            'Fragrances & Perfumes',
            'Traditional Remedies & Herbs',
            'Wellness Teas',
            'Essential Oils',
            'Grooming Tools',
            'Massage & Spa Items',
            'Oral Care',
            "Men's Grooming",
            'Baby Care Products',
        ],
    },
    {
        id: 'learning',
        name: 'Learning & Experiences',
        icon: '📚',
        subcategories: [
            'Language Learning (Books, Audio, Flashcards)',
            'Cooking Classes (Virtual/In-Person)',
            'Dance Classes',
            'Music Lessons',
            'Art & Craft Workshops',
            'Cultural History Books',
            "Children's Educational Books",
            'Recipe Books & Cookbooks',
            'Language Tutoring Services',
            'Cultural Tours (Virtual/In-Person)',
            'DIY Kits with Instructions',
            'Online Courses',
            'Cultural Documentaries',
            'Educational Games',
        ],
    },
    {
        id: 'events',
        name: 'Events & Services',
        icon: '🎉',
        subcategories: [
            'Cultural Festival Tickets',
            'Concert & Performance Tickets',
            'Catering Services',
            'Event Planning (Weddings, Parties)',
            'Traditional Ceremony Services',
            'Photography Services',
            'Videography Services',
            'DJ & Entertainment Services',
            'Venue Rentals',
            'Decoration Services',
            'Translation Services',
            'Cultural Consultation',
            'Community Meetups & Gatherings',
            'Cooking Services (Private Chef)',
            'Cultural Classes & Workshops',
        ],
    },
];
